# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=2.2.0
mod.group=com.github.kd_gaming1
mod.id=scaleme
mod.name=ScaleMe

# Global dependencies
deps.fabric_loader=0.17.3
deps.yarn_mappings=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.midnightlib_version=[VERSIONED]
deps.modmenu_version=[VERSIONED]
deps.owo_version=[VERSIONED]