name: build
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ] # Run on pushes to master and on tags like v1.0.0
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: "!startsWith(github.ref, 'refs/tags/')" # Don't upload to artifacts on tag pushes
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - name: create release
        if: startsWith(github.ref, 'refs/tags/') # Only run this step on tag pushes
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar